### PR TITLE
Update easylistlithuania.txt

### PR DESCRIPTION
**Pull request by leekleak**
Seems to work fine now.

As for the side effects, I am not sure (I don't use the site at all), but it looks ok at a glance :)

### CODE REVIEW

**Comment by iibett** [comment]
I can't reproduce any ads on delfi with Ublock origin, what adblock do you use?

**Comment by leekleak** [comment]
ublock origin as well. As a reference here is how the site looks without those filter rules:
image
And here with them:
image

**Comment by DandelionSprout** [comment]
The thing I find most interesting with PR, though not in a bad way as such, is `delfi.lt##*[style*="float: right;"]`, where the `*` would normally be superfluous, and that `delfi.lt##[style*="float: right"]` would work the same way but marginally better.

As such, I accept the intellectual challenge of looking into the site to look for the ads.

That being said, which lists are you (leekleak) using, just to be sure?

**Comment by leekleak** [comment]
Just the uBlock origin defaults + this

**Comment by DandelionSprout** [comment]
I'm soon to head out to a shower, doctor appointment, and haircut, but can you test turning on "AdGuard - Ads" in the uBO settings and that helps anything?

**Comment by iibett** [comment]
Do you use any other adblocker along side Ublock origin also what browser are you using also can you post Ublock origin troubleshooting Information.

**Comment by leekleak** [comment]
> I'm soon to head out to a shower, doctor appointment, and haircut, but can you test turning on "AdGuard - Ads" as well in the uBO settings and see if that helps anything?

Yup, that removed the ads as well.

**Comment by leekleak** [comment]
> Do you use any other adblocker alongside Ublock origin also what browser are you using also can you post Ublock origin troubleshooting Information.

Don't remember the exact version but for the browser it's the latest release of librewolf. As for the adblockers, there's only uBlock.

**Comment by DandelionSprout** [comment]
I've tried telling the uBlock Origin team for ***years*** to enable AdGuard Base Filter by default, and they keep making seemingly imaginary fake reasons as to why they still haven't.

Seems like I'll go on a borrowing trip to AdGuard's entries and paste them into this list then.

**Comment by iibett** [comment]
I fixed it now it should be good @DandelionSprout

**Comment by leekleak** [comment]
yep :)

**Pull request closed without merging**
